services:
  homeassistant-price-tracker:
    container_name: homeassistant-price-tracker
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./configuration.yaml:/config/configuration.yaml
      - ../custom_components/price_tracker:/config/custom_components/price_tracker
    restart: unless-stopped
    privileged: true
    environment:
      - TZ=Asia/Seoul
    ports:
      - "8123:8123"
